fail_fast: true
repos:
- hooks:
  - entry: isort -sp setup.cfg
    id: isort
    language: system
    language_version: python
    name: isort
    types:
    - python
  - entry: black
    id: black
    language: system
    language_version: python
    name: black
    types:
    - python
  - entry: python -c 'import sys; import subprocess; subprocess.run(["mypy", "--ignore-missing-imports"]
      + sys.argv[1:])'
    id: mypy
    language: system
    language_version: python
    name: mypy
    types:
    - python
    verbose: true
  - entry: flake8
    id: flake8
    language: system
    language_version: python
    name: flake8
    types:
    - python
  repo: local
