# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/

language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - ./manage.py lint --pylint
  - py.test --verbose --cov dontforget

after_success:
  - codecov
