# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/

language: python

python:
  - 3.5

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install codecov
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c 'CREATE DATABASE dontforget_test;'

script:
  - ./manage.py lint --pylint
  - py.test --verbose --cov dontforget

after_success:
  - codecov
