# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
os: osx
language: python
cache: pip
python:
  - 3.6
services:
  - postgresql
addons:
  postgresql: "9.6"
  hosts:
  - postgresql
install:
  - pip install -U codecov pipenv
  - pipenv install --dev
before_script:
  - pip freeze
  - psql -U postgres -c 'CREATE USER dontforget;'
  - psql -U postgres -c 'CREATE DATABASE dontforget_test;'
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE dontforget_test TO dontforget;'
script:
  - flake8
  - py.test --verbose --cov dontforget
after_success:
  - codecov
after_failure:
  - dmesg | tail -n 100
