version: "3.5"

services:
  dontforget:
    container_name: dontforget
    build: .
    # TODO feat: use a production WSGI server on Docker Compose
    command: poetry run flask run --host 0.0.0.0 --port 8008
    ports:
      - 8008:8008
    env_file:
      - .env
    environment:
      FLASK_APP: autoapp.py
      FLASK_ENV: production
    volumes:
      - .:/dontforget

# TODO refactor: remove unused services and their related dead code
#telegram:
#  build: .
#  command: poetry run flask telegram
#  links:
#    - postgresql
#  volumes:
#    - .:/dontforget
#  environment:
#    - DONTFORGET_ENV=prod
