flask:
  build: .
  command: echo python manage.py runserver --host 0.0.0.0 --port 5000 --debug --reload
  volumes:
    - .:/dontforget
  ports:
    - "6660:5000"

telegram:
  build: .
  command: python manage.py telegram
  volumes:
    - .:/dontforget
  environment:
    - DONTFORGET_ENV=prod
    - UI_MODULE_NAME=telegram_bot  # Docker doesn't work with Cocoa Dialog as UI
