[tool.black]
line-length = 120

[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["Augusto Wagner Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
jinja2 = "*"
psycopg2 = "*"
flask = "*"
flask-migrate = "*"
flask-sqlalchemy = "*"
flask-script = "*"
markupsafe = "*"
sqlalchemy = "*"
werkzeug = "*"
arrow = "*"
maya = "*"
prettyconf = "*"
telepot = "*"
marshmallow = {version = "*", allows-prereleases = true}
pyobjc-core = "*"
pyobjc-framework-cocoa = "*"
todoist-python = "*"
tapioca-toggl = "*"
toml = "*"
simple-settings = {version = "*", extras = ["toml"]}

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
"flake8-blind-except" = "*"
"flake8-bugbear" = "*"
"flake8-comprehensions" = "*"
"flake8-debugger" = "*"
"flake8-docstrings" = "*"
"flake8-isort" = "*"
"flake8-mypy" = "*"
"flake8-polyfill" = "*"
"flake8-pytest" = "*"
"flake8" = "*"
flake8-quotes = "*"
flake8-nitpick = "*"
pylint = "*"
mypy = "*"
ipython = "*"
ipdb = "*"
pre-commit = {version = "*", allows-prereleases = true}
