[tool.black]
line-length = 120

[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["W. Augusto Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jinja2 = "*"
psycopg2-binary = "*"
click = "*"
markupsafe = "*"
memoized-property = "*"
arrow = "*"
pendulum = "*"
marshmallow = "*"
todoist-python = "*"
tapioca-toggl = "*"
toml = "*"
environs = "*"
deprecated = "*"
python-redmine = "*"
autorepr = "*"
pluginbase = "*"
imbox = "*"
jmespath = "*"
rumps = "*"
apscheduler = "*"
appdirs = "*"
"ruamel.yaml" = "*"
google-api-python-client = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
TogglPy = "*"
keyring = "*"

[tool.poetry.scripts]
dontforget = "dontforget.app:start_on_status_bar"
pipe = "dontforget.pipes:pipe"

[tool.poetry.dev-dependencies]
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
pylint = "*"
ipython = "*"
ipdb = "*"

[tool.nitpick]
style = ["https://raw.githubusercontent.com/andreoliwa/nitpick/develop/nitpick-style.toml"]
