[tool.black]
line-length = 120

[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["W. Augusto Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
jinja2 = "*"
psycopg2 = "*"
flask = "*"
flask-migrate = "*"
flask-sqlalchemy = "*"
markupsafe = "*"
sqlalchemy = "*"
werkzeug = "*"
arrow = "*"
maya = "*"
telepot = "*"
marshmallow = "*"
pyobjc-core = {version = "^5.2",optional = true}
pyobjc-framework-cocoa = {version = "^5.1",optional = true}
todoist-python = "*"
tapioca-toggl = "*"
toml = "*"
environs = "*"
deprecated = "*"

# Those optional packages are only available on macOS. To install them:
# poetry install --extras macos
python-redmine = "^2.2"
autorepr = "^0.3.0"
[tool.poetry.extras]
macos = ["pyobjc-core", "pyobjc-framework-cocoa"]

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
"flake8-blind-except" = "*"
"flake8-bugbear" = "*"
"flake8-comprehensions" = "*"
"flake8-debugger" = "*"
"flake8-docstrings" = "*"
"flake8-isort" = "*"
"flake8-mypy" = "*"
"flake8-polyfill" = "*"
"flake8-pytest" = "*"
"flake8" = "*"
flake8-quotes = "*"
flake8-nitpick = "*"
pylint = "*"
mypy = "*"
ipython = "*"
ipdb = "*"
pre-commit = {version = "*", allows-prereleases = true}
