[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["Augusto Wagner Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "3.6"
jinja2 = "*"
psycopg2 = "*"
flask = "*"
flask-migrate = "*"
flask-sqlalchemy = "*"
flask-script = "*"
markupsafe = "*"
sqlalchemy = "*"
werkzeug = "*"
arrow = "*"
itsdangerous = "*"
maya = "*"
prettyconf = "*"
python-dateutil = "*"
telepot = "*"
marshmallow = "*"
pyobjc-core = "*"
pyobjc-framework-cocoa = "*"
todoist-python = "*"
tapioca-toggl = "*"
toml = "*"
simple-settings = {version = "*", extras = ["toml"]}

[tool.poetry.dev-dependencies]
black = "*"
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
nitpick = "*"
