[tool.black]
line-length = 120

[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["W. Augusto Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jinja2 = "*"
psycopg2-binary = "*"
flask = "*"
flask-migrate = "*"
flask-sqlalchemy = "*"
markupsafe = "*"
sqlalchemy = "*"
werkzeug = "*"
arrow = "*"
maya = "*"
telepot = "*"
marshmallow = "*"
pyobjc-core = {version = "^6.1",optional = true}
pyobjc-framework-cocoa = {version = "^6.1",optional = true}
todoist-python = "*"
tapioca-toggl = "*"
toml = "*"
environs = "*"
deprecated = "*"
python-redmine = "*"
autorepr = "*"
pluginbase = "*"
imbox = "*"
jmespath = "*"
rumps = "*"
apscheduler = "*"
appdirs = "*"

[tool.poetry.scripts]
dontforget = "dontforget.app:start_on_status_bar"

[tool.poetry.extras]
# Those optional packages are only available on macOS. To install them:
# poetry install --extras macos
macos = ["pyobjc-core", "pyobjc-framework-cocoa"]

[tool.poetry.dev-dependencies]
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
pylint = "*"
ipython = "*"
ipdb = "*"

[tool.nitpick]
style = ["https://raw.githubusercontent.com/andreoliwa/nitpick/develop/nitpick-style.toml"]
