[tool.black]
line-length = 120

[tool.poetry]
name = "dontforget"
version = "0.1.0"
description = "Don't forget to complete your tasks, using Todoist, Toggle and Node-RED integrations"
authors = ["W. Augusto Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jinja2 = "*"
click = "*"
memoized-property = "*"
arrow = "*"
pendulum = "*"
marshmallow = "*"
todoist-python = "*"

# TODO: keep only one of these Toggl packages:
togglCli = "*"
TogglPy = "*"
tapioca-toggl = "*"

toml = "*"
environs = "*"
deprecated = "*"
python-redmine = "*"
autorepr = "*"
pluginbase = "*"
imbox = "*"
jmespath = "*"
rumps = "*"
apscheduler = "*"
appdirs = "*"
"ruamel.yaml" = "*"
google-api-python-client = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
keyring = "*"
#clib = { path = "../python-clib", develop = true }
clib = { git = "https://github.com/andreoliwa/python-clib.git", branch = "develop" }
vcrpy = "*"
maya = "*"
joblib = "*"
iterfzf = '*'

[tool.poetry.scripts]
fo = "dontforget.cli:main"
dontforget = "dontforget.cli:main"
pipe = "dontforget.pipes:pipe"

[tool.poetry.dev-dependencies]
faker = "*"
coverage = "*"
factory-boy = "*"
pytest = "*"
pytest-cov = "*"
pytest-runfailed = "*"
pylint = "*"
ipython = "*"
jedi = "<0.18.0" # TODO: remove when this is fixed https://github.com/ipython/ipython/issues/12745
ipdb = "*"

[tool.nitpick]
style = ["https://raw.githubusercontent.com/andreoliwa/nitpick/develop/nitpick-style.toml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
