# The following values can either be set with settings.toml or environment variables
TOGGL_API_TOKEN = ''
TODOIST_USER = ''
TODOIST_PASSWORD = ''

icons = [
  'Fire',
  'LargeRedCircle',
  'FourLeafClover',
  'MediumWhiteCircle',
]

[counts]
Fire = 0
LargeRedCircle = 0
FourLeafClover = 0

[go_home]
hours = 8
toggl_clients = ['Toggl Client Name 1', 'Toggl Client Name 2']
toggl_add_projects = ['Work Pause']
todoist_project = 'Todoist Project Name'
todoist_task = 'Go home!'
