[[gmail]]
email = "your.personal.email@gmail.com"
interval = {minutes = 10}
password = "<your app password here>"

[[gmail]]
email = "your.work.email@your.company.gsuite.email.com"
interval = {seconds = 30}
password = "<your work email app password>"
