[[gmail]]
interval = { minutes = 10 }
email = "your.personal.email@gmail.com"
password = "<your app password here>"

[[gmail]]
interval = { seconds = 30 }
email = "your.work.email@your.company.gsuite.email.com"
password = "<your work email app password>"
