[source.redmine]
url = "${REDMINE_URL}"
api_token = "${REDMINE_API_TOKEN}"

[target.todoist]
api_token = "$TODOIST_API_TOKEN"
id = "{{ redmine.id }}"
content = "{{ redmine.subject }}"
due = "{{ redmine.due_date }}"
